/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// module.exports = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };
module.exports = {
  Lab : [
    
    // 'intro',
    {
      'Experiment 0':[
        {
          type: 'doc',
          id: 'lab-handouts/exp0w', // document id
          label: 'Wednesday Batch', // sidebar label
        },
        {
          type: 'doc',
          id: 'lab-handouts/exp0t', // document id
          label: 'Thursday Batch', // sidebar label
        }, 
      ],
    },
    {
      'Experiment 1':[
        {
          type: 'doc',
          id: 'lab-handouts/exp1w', // document id
          label: 'Wednesday Batch', // sidebar label
        },
        {
          type: 'doc',
          id: 'lab-handouts/exp1t', // document id
          label: 'Thursday Batch', // sidebar label
        }, 
      ],
    },
  ],
  sw: [
    {
      Quartus: [
        {
          type: 'doc',
          id: 'windows/Installation', // document id
          label: 'Windows Installation', // sidebar label
        },
        'tutorial-basics/create-a-page',
      ],
    }  
  ],
  sl: [
    {
      Quartus: [
        {
          type: 'doc',
          id: 'linux/Installation', // document id
          label: 'Linux Installation', // sidebar label
        },
        
      ],
    }  
  ],
}